### ISSUE TITLE
Migration of Babel 7.x

### ISSUE THREAD

**Issue by JacopKane** [jaredpalmer/backpack#106]
Created a PR for this
https://github.com/jaredpalmer/backpack/pull/105

**Comment by juhaelee** [comment]
@jaredpalmer are there any plans to publish backpack@next for people who want to use babel7?

**Comment by jaredpalmer** [comment]
just published the `next` branch as 0.8.0-0

**Comment by juhaelee** [comment]
@jaredpalmer thanks! I think there's a problem though, I believe that backpack-core@0.8.0-0 needs to use babel-preset-backpack@0.8.0-0 ([currently it's using 0.5.0](https://github.com/jaredpalmer/backpack/blob/next/packages/backpack-core/package.json#L18))

**Comment by shawntax** [comment]
+1
