### ISSUE TITLE
There is a severe bug on backpack, solution on this issue description

### ISSUE THREAD

**Issue by Mark083** [jaredpalmer/backpack#110]
As described on this [issue](https://github.com/jaredpalmer/backpack/issues/109) there is a bug on typescript example as pointed by @[Jeffrey Westerkamp] on  [this answer](https://stackoverflow.com/a/48600351/9217154)

The bug is on [this](https://github.com/jaredpalmer/backpack/blob/8db85f4b27734184343c0b5469dc74eaef8bd524/examples/with-typescript/src/main.ts#L33) line and the solution gave by @[Jeffrey Westerkamp] was: 

`private getPort = (): number => parseInt(process.env.PORT) || 3000;`

**Comment by JacopKane** [comment]
Fixed on https://github.com/jaredpalmer/backpack/pull/112

**Comment by Mark083** [comment]
ok, thanks
