### ISSUE TITLE
Publish master and next branch

### ISSUE THREAD

**Issue by JacopKane** [jaredpalmer/backpack#119]
I've arranged the changes in an order we talked before @jaredpalmer 

You should simply do a:
```bash
git pull
git checkout master
yarn publish # 0.6.0
git checkout next
yarn publish --tag next  # 1.0.0@next
```

**Comment by jaredpalmer** [comment]
Epic. Will push later tonight or tomorrow

**Comment by maximeshr** [comment]
Any news on this one ?
I can't wait to test this two new versions 😜

**Comment by jaredpalmer** [comment]
Done.
