### ISSUE TITLE
negative build times

### ISSUE THREAD

**Issue by glensargent** [jaredpalmer/backpack#121]
Build times turn up as negative 
<img width="300" alt="3620375444db26948bd3e5617cf190a9" src="https://user-images.githubusercontent.com/10516792/37558285-6288da4a-2a09-11e8-9ceb-09cb6cc6195e.png">

**Comment by mxstbr** [comment]
Backpack's too fast.

**Comment by mxstbr** [comment]
It compiles your code before you've even finished writing it.

**Comment by jaredpalmer** [comment]
Hmmmmm.

**Comment by dashed** [comment]
It needs to be faster.
