### ISSUE TITLE
Getting backpack working with Ava

### ISSUE THREAD

**Issue by alechp** [jaredpalmer/backpack#128]
Any advice on how to get around this?

---

### Error
> Seems to stem from Babel 6 (Backpack) & Babel 7 (Ava) incompatibility  

```bash
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /...path.../node_modules/backpack-core/babel.js
```

### Backpack Core versions tried

* **^0.7.0**
* **^0.8.0-0**

### Relevant Resources
* [Plugin/Preset files are not allowed to export objects, only functions. · Issue #6808 · babel/babel · GitHub](https://github.com/babel/babel/issues/6808)
> This thread shows how to fix this error (ie. just upgrade babel from 6 -> 7)  

* [Getting ready for Babel 7 · Issue #1598 · avajs/ava · GitHub](https://github.com/avajs/ava/issues/1598)
> Relevant Ava plugins for Babel 7  

### Related Issues
* [Migration of Babel 7.x · Issue #106 · jaredpalmer/backpack · GitHub](https://github.com/jaredpalmer/backpack/issues/106)
> Backpack thread about **v0.8.0-0**  

* [Plugin/Preset files are not allowed to export objects, only functions ](https://github.com/jaredpalmer/backpack/issues/126)
> Found this duplicate after creating this issue

### Config

**.babelrc**
```json
{
  "presets": [
    "backpack-core/babel",
    "@ava/stage-4",
    "@ava/transform-test-files"
  ]
}

```

### Looking for a hack-through

As suggested [here](https://github.com/jaredpalmer/backpack/tree/HEAD@%7B2018-05-12T02:58:25Z%7D#issuecomment-388525216), tried to see if forcing babel-preset-back from version 0.5.0 to 0.8.0-0 would resolve the issue. But still receiving the issue.

### Control group
Sample repo of Ava working with Babel 7: [https://github.com/servexyz/npm-starter](https://github.com/servexyz/npm-starter)

**Comment by sandeepDevJs** [comment]
hello there, any update? how did you solve this?
