### ISSUE TITLE
Does this project mean we don't need node_modules?

### ISSUE THREAD

**Issue by berkeleybross** [jaredpalmer/backpack#130]
I raised a question in stackoverflow about how to deploy the smallest package to AWS Lambda (https://stackoverflow.com/questions/51460962/bundling-and-tree-shaking-node-modules-into-a-single-file)

Does this project mean that you only need to upload the produced main.js file? Or do you still need to npm install on the production server (or equivalent)? If you still need node_modules, when would you use this project vs a babel build step?

I notice that when I run backpack, it creates a file much larger than my source code which seemingly contains my node_modules folder, which led me to believe that node_modules isn't necessary. However when I run it, it says 'cannot find module "fs-extra"'. It runs fine when run from a folder with node_modules though.

Thanks!

**Comment by adambrgmn** [comment]
Hey,
I just did a very naive test for the exact same reason. But note that I have not yet tried to deploy anything to Lambda.

But I had some luck using `backpack.config.js` with this setup for webpack:

```js
module.exports = {
  webpack(config, _, webpack) {
    return Object.assign({}, config, {
      externals: undefined,
      plugins: config.plugins.filter(
        plugin => plugin.constructor !== webpack.BannerPlugin,
      ),
    });
  },
};

```

It resulted in a main.js file with everything bundled. Except node standard library (`fs`, `path`, etc.).

The `externals`-prop is by default used to skip bundling of dependencies, here I just reset it and let Webpack bundle everything.

The only issue I encountered with this setup was that Backpack [injects a banner containing a require](https://github.com/jaredpalmer/backpack/blob/cb8fcb982949f166fe8d15315abc673ec3f1d47d/packages/backpack-core/config/webpack.config.js#L124) to `source-map-support` – which is required to, not so surprising, support source maps. By filtering out every instance of the `BannerPlugin` the banner will not be injected. Note that this also results in disabling source-map support. So one might want to also do something to work around this (maybe check for `options.env === 'production'` or something similar).

Hopefully this will lead you somewhere.
