### ISSUE TITLE
Doesn't work with the latest version of Next.js

### ISSUE THREAD

**Issue by DPr00f** [jaredpalmer/backpack#137]
Next uses a version 7 of babel and backpack uses version 6
This causes conflicts and one of the builds won't run.
Since backpack uses the same structure as next and doesn't allow you to specify a custom `.babelrc` file those have to be shared.

I managed to get this running by forking it and updating the dependencies.
But I'm still not sure that's the right solution so I won't open a PR.
It's a solution but not future proof. Def the best solution would be to be able to specify a `.babelrc` file in `backpack.config.js` other than the one on the root.

**Comment by simllll** [comment]
I've added nuxt js 2 and webpack 4 support here:
https://github.com/hokify-dev/backpack-core/commits/master

main changes: 
* ugprade to webpack 4
* upgraded dependencies
* removed json loader (webpack4 can do this itself now)

**Comment by jaredpalmer** [comment]
Fixed with 0.8
