### ISSUE TITLE
Update dependency around event-stream

### ISSUE THREAD

**Issue by kitsuyui** [jaredpalmer/backpack#152]
Some problem found on newer version of `event-stream` in these days. https://github.com/dominictarr/event-stream/issues/115

`backpack-core` has following dependency, but fortunately currently depending version `v3.3.0` is safe.
- backpack-core -> nodemon -> pstree.remy -> ps-tree -> event-stream

I think that backpack-core dependency should be update nodemon version to `v1.18.7` for future safety.

## Reference

- `nodemon` (Fixed: https://github.com/remy/nodemon/pull/1470 )
- `pstree.remy` (Removed `ps-tree` dependency: https://github.com/remy/pstree/pull/2)
- `ps-tree` (Locks `event-stream` to `v3.3.4` as safe version: https://github.com/indexzero/ps-tree/pull/34)
- `event-stream` (Removed insecure version: https://github.com/dominictarr/event-stream/issues/115)

**Comment by andres-valdes** [comment]
Opened #153 for this purpose

**Comment by bildo17** [comment]
The issue has now been updated. I ran `npm install nodemon@latest -D` and it worked like a charm.

**Comment by andres-valdes** [comment]
@bildo17 Yes, nodemon has resolved this issue, but backpack-core still depends on an infected version of nodemon.

**Comment by kitsuyui** [comment]
Solved by https://github.com/jaredpalmer/backpack/pull/153 🎉
