### ISSUE TITLE
Add out of the box TypeScript support with @babel/preset-typescript

### ISSUE THREAD

**Issue by etienne-dldc** [jaredpalmer/backpack#174]
Hi !

I would like to propose to add support for TypeScript by default using `@babel/preset-typescript`.

I believe this can be done by adding the preset to the babel config and adding `.ts` in the `.test` of the `babel-loader`.

I can make a PR 😉

**Comment by NotoriousGOR** [comment]
@etienne-dldc, can you do it, please? Lol Fixing to use this library for work and I'm shocked it doesn't have TS already

**Comment by etienne-dldc** [comment]
Hi @NotoriousGOR, sorry but I'm not using backpack (since quite a long time actually, I opened this issue 3 years ago) and I believe it is not maintain anymore...

If you need to run TS I recommend you to take a look at [esbuild-kit/tsx](https://github.com/esbuild-kit/tsx)

✌️
