### ISSUE TITLE
Backpack artifacts `source-map-support/register` not found in docker container

### ISSUE THREAD

**Issue by vivere-dally** [jaredpalmer/backpack#189]
I'm building my node server with backpack via `backpack build`. I'm copying the build results from `build` to my docker image. After that, I run it with `node main.js`. This is when I'm encountering the error `source-map-support/register`.

I tried everything that I found in the other issues opened here about this topic and nothing worked.

Dockerfile:
```
FROM node:12.21-alpine

ENV NODE_ENV=production

RUN mkdir -p /home/app

COPY ./build /home/app

WORKDIR /home

CMD ["node", "./app/main.js"]
```

As the node app, I'm playing with [this example](https://github.com/jaredpalmer/backpack/tree/master/examples/basic).

#165 & #42 did not help.

**Comment by p21nc3** [comment]
Hey [vivere-dally](https://github.com/vivere-dally), 

Are you still facing this issue? [source-map-support/register].
