### ISSUE TITLE
I want to use others NODE_ENV 

### ISSUE THREAD

**Issue by Kntt** [jaredpalmer/backpack#67]
In the use of backpack process, only two kinds of NODE_ENV, production & development, how can i  definied NODE_ENV by myself, like beta, test ...

**Comment by shawon1220** [comment]
i think must modify bin/dev and bin/build
const serverConfig = userConfig.webpack
      ? userConfig.webpack(defaultConfig, options, webpack)
      : defaultConfig(options)

then add backpack.config.js at root dir

module.exports = {
  webpack: (defaultConfig, options, webpack) => {
  	options.env='uat';
  	let config=defaultConfig(options);
       return config
  }
}

**Comment by Kntt** [comment]
I also wrote here, but I did not find that you can use defaultConfig (opts), very grateful

**Comment by Kntt** [comment]
![image](https://user-images.githubusercontent.com/20291026/28977285-011206ba-7974-11e7-849e-48395f4dac31.png)
Through this method, redefine webpack.DefinePlugin, temporarily solve this problem
