### ISSUE TITLE
Node 8 (async/await)

### ISSUE THREAD

**Issue by mxstbr** [jaredpalmer/backpack#83]
The backpack Babel preset does a bunch of stuff to make `async/await` supported in environments that don't support it: 

https://github.com/jaredpalmer/backpack/blob/5fa5008fb0cfaa9a18178230544e42c945dcdf49/packages/babel-preset-backpack/index.js#L24-L41

The issue is that as of the Node 8 LTS release it's totally unnecessary since it supports `async/await` out of the box! To get it to build with vanilla `async/await` (not transpiled to generators) I had to opt-out of the shared Babel config and basically just run with this `.babelrc`:

```JSON
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": "current"
        },
        "useBuiltIns": true,
        "exclude": [
          "babel-plugin-transform-regenerator",
          "transform-async-to-generator"
        ]
      }
    ]
  ],
  "plugins": [
    "transform-flow-strip-types",
    "transform-object-rest-spread",
    "babel-plugin-transform-react-jsx",
    "syntax-dynamic-import"
  ]
}
```

It'd be A+++ super awesome if backpack did the right thing™️ for Node 8 by default, i.e. didn't transpile generators at all and didn't include `regenerator` in the bundle. :blush:

**Comment by jaredpalmer** [comment]
Very much agree

**Comment by jaredpalmer** [comment]
Definitely a breaking change though.

**Comment by mxstbr** [comment]
Maybe we could use `process.version` to include things optionally if a user is on Node < 8?

**Comment by yoyo837** [comment]
It is best to be able to automatically sniff using a different configuration.
