### ISSUE TITLE
Can you release last commit ?

### ISSUE THREAD

**Issue by biigpongsatorn** [jaredpalmer/backpack#93]
i would like to use options.env = staging in build command however currently, the options.env is fixed in production only. Now my pull request #89 fixed this issue. Would it be possible to release last commit to npm.

big thanks :)

**Comment by wakamatsu** [comment]
I would like to release latest version. I use this at my project that will release shortly. So I'm waiting for resolve this problem.[#89](https://github.com/jaredpalmer/backpack/pull/89) 
thanks a lot.

**Comment by biigpongsatorn** [comment]
@wakamatsu Now i resolve this issue. My solution is create new environment variable and use that instead NODE_ENV

example :

`config.plugins[0].definitions['process.env.NEW_NODE_ENV'] = 'master'`

**Comment by wakamatsu** [comment]
@biigpongsatorn
Thanks a lot! At result, I edited backpack.config.js. And now, I can refer env values.

**Comment by biigpongsatorn** [comment]
@wakamatsu You're welcome :)

**Comment by mxstbr** [comment]
Released in v0.5.0 12 hours ago by @jaredpalmer!
